add_newline = false

[git_branch]
symbol = " "
[git_status]
format = "\\($ahead_behind$conflicted$modified$staged$renamed$deleted$untracked\\) "
conflicted = "[✘${count}](red)"
up_to_date = "[✔](green)"
ahead = "⇡${count}"
behind = "⇣${count}"
modified = "[+${count}](red)"
staged = "[●${count}](yellow)"
diverged = "⇡${ahead_count}⇣${behind_count}"
renamed = "[»${count}](yellow)"
untracked = "[…](white)"
deleted = "[-${count}](yellow)"
style = ""

[lua]
symbol = " "
[nodejs]
symbol = " "
[package]
symbol = " "
[python]
symbol = " "
[rust]
symbol = " "
